name: audio_capture
description: "Get the current application audio stream"
version: 0.0.1
#homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  permission_handler: ^11.4.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^18.0.0

flutter:
  plugin:
    platforms:
#      android:
#        package: com.github.BBeBeeX.audio_capture
#        pluginClass: AudioCapturePlugin
#      ios:
#        pluginClass: AudioCapturePlugin
#      linux:
#        pluginClass: AudioCapturePlugin
#      macos:
#        pluginClass: AudioCapturePlugin
      windows:
        pluginClass: AudioCapturePluginCApi

ffigen:
  name: 'audio_capture_bindings'
  description: 'FFI bindings to the audio capture DLL.'
  output: 'lib/src/audio_capture_bindings.dart'

  headers:
    entry-points:
      - 'native/src/audio_capture.h'

  compiler-opts:
    - '-Inative/audio_capture'
    - "-Inative/miniaudio/extras/miniaudio_split"

  preamble: |
    // Auto-generated file, do not edit.
    // Generated by `package:ffigen`.